language: node_js
node_js:
- "10"
notifications:
  email: false
cache:
  directories:
  - node_modules
before_install:
  - npm install -g npm@^2
script:
  - npm run test
after_success:
  - npm run semantic-release